# .github/workflows/ci.yml
name: ci

on: [push, pull_request]

jobs:
  ci:
    uses: catalyst/catalyst-moodle-workflows/.github/workflows/ci.yml@v2-groups
    # secrets:
      # Required if you plan to publish (uncomment the below)
      # moodle_org_token: ${{ secrets.MOODLE_ORG_TOKEN }}
    with:
      #Grunt fails due to CSS styling needing an !important.
      disable_grunt: true